variables:
  # Для переменных ниже используются значения по умолчанию:
  # - из группы проектов AI
  # - из встроенных в образы сборщиков переменных
  # Раскомментируйте для переназначения или добавьте значение в настройках проекта в GitLab
  # https://gitlab.ptsecurity.com/ai/ai-docker-base/docker-vscode-plugin-builder
  # AI_PLUGIN_CI_IMAGE: docker.ptsecurity.ru/ai-builder-linux-vscode:latest
  # NPM_CONFIG_REGISTRY: "https://repo.ptsecurity.ru/artifactory/api/npm/npmjs/"

stages:
  - build

Build vsix package:
  stage: build
  image: $AI_PLUGIN_CI_IMAGE
  tags:
    - linux
    - docker
    - build
  script:
    - ./build_on_server.sh
    - crossbuilder run UploadArtifacts
  when: on_success
